apiVersion: apps/v1
kind: Deployment
metadata:
  name: myoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myoperator
  template:
    metadata:
      labels:
        name: myoperator
    spec:
      serviceAccountName: myoperator
      containers:
        - name: myoperator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - myoperator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "myoperator"
