apiVersion: operator-utils.example.io/v1alpha1
kind: EnforcingCRD
metadata:
  name: example-enforcingcrd
spec:
  resources:
    - object: 
        apiVersion: v1
        kind: ConfigMap
        metadata:
          creationTimestamp: "2020-03-30T16:24:08Z"
          name: test-configmap
          namespace: test-enforcingcrd
        data:
          ciao: ciao
    - object:
        apiVersion: route.openshift.io/v1
        kind: Route
        metadata:
          name: test-route
          namespace: test-enforcingcrd
        spec:
          host: grafana-istio-system.apps.cluster-4cac.sandbox456.opentlc.com
          tls:
            termination: reencrypt
          to:
            kind: Service
            name: grafana
            weight: 100
          wildcardPolicy: None    
